### ISSUE TITLE
Disable compile failure on unused symbol

### ISSUE THREAD

**Issue by johnsonr** [atomist-seeds/spring-sdm#22]
This makes sense as a best practice, but complicates exploration when people are commenting things out etc.

**Comment by ddgenome** [comment]
Here is the TypeScript settings causing this:

https://github.com/atomist-seeds/spring-sdm/blob/f8af33dbb3fe2dbb96d0574260bb3e4a3ac7d5a1/tsconfig.json#L21

Assuming it is unused imports that are causing you issues, unlike the related TSLint rule, https://palantir.github.io/tslint/rules/no-unused-variable/, there is no way to selectively enable and disable this for different types of unused locals.

Disabling the compiler option and enabling the TSLint rule causes TSLint to print a warning saying the TSLint rule is deprecated on TypeScript 2.9+, suggesting the compiler option.

How would you like to proceed?

**Comment by johnsonr** [comment]
Can we disable both compiler error and tslint rule? I think for exploration people need to be able to comment stuff in and may end up with both unused imports and unused variables.
